# Generated by Django 2.1.7 on 2019-06-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190611_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
