# Generated by Django 2.1.7 on 2019-06-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('info', 'Sky Blue'), ('warning', 'Yellow'), ('danger', 'Red')], default='primary', max_length=250),
        ),
    ]
