# Generated by Django 2.1.7 on 2019-08-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190614_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='img/avatar/empty-avatar.png', upload_to='img/avatars'),
        ),
    ]
