# Generated by Django 2.1.7 on 2019-08-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
