# Generated by Django 2.1.7 on 2019-09-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_category_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(True, 'Visible'), (False, 'Hidden')], default=True),
        ),
    ]
