# Generated by Django 2.1.7 on 2019-06-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='body',
            new_name='bio',
        ),
    ]
