# Generated by Django 2.1.7 on 2019-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190621_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/empty-avatar.png', upload_to='img/'),
        ),
    ]
